import json

notebook = {
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# 📊 Analyse Exploratoire des Données de Capteurs Plantaires (EDA)\n",
    "\n",
    "Ce notebook permet la réalisation d'une analyse exploratoire des signaux de capteurs plantaires et des événements ou annotations associés dans le cadre du TD.\n",
    "\n",
    "Il a été conçu pour suivre la démarche suivante :\n",
    "1. **Chargement et Intégrité** : Concaténation des signaux (données inertielles et de pressions) et fusion avec les annotations.\n",
    "2. **Analyse Statistique et Outliers** : Visualisation de la distribution et détection visuelle des valeurs aberrantes.\n",
    "3. **Visualisation Spatio-Temporelle** : Tracés de l'activation plantaire, données IMU et trajectoire 2D du Centre de Pression (CoP).\n",
    "4. **Comparaison Inter-Classes** : Comparaison de la dynamique (force totale moyennée) de plusieurs actions (ex: Standing vs Walking)."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "import os\n",
    "import warnings\n",
    "\n",
    "# Configuration esthétique des graphiques et désactivation des warnings mineurs\n",
    "warnings.filterwarnings('ignore')\n",
    "sns.set_theme(style=\"whitegrid\")\n",
    "plt.rcParams['figure.figsize'] = (12, 6)\n",
    "plt.rcParams['font.size'] = 12\n",
    "\n",
    "# Paramètres globaux correspondant à l'arborescence (à adapter selon le répertoire d'exécution)\n",
    "BASE_DIR = os.path.join(\".\", \"DataChallenge_donneesGlobales\") # Dépend de là où est lancé le notebook. Modifier en '.' si besoin.\n",
    "PLANTAR_DIR = os.path.join(BASE_DIR, \"Plantar_activity_trie\")\n",
    "EVENTS_DIR = os.path.join(BASE_DIR, \"Events\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 1. Chargement et Intégrité des Données\n",
    "\n",
    "Nous allons aligner temporellement les classes d'actions sur les enregistrements des signaux des capteurs plantaires (fréquence 100 fps) via `Timestamp Start` et `Timestamp End`."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "def load_and_merge_data(subject_id='01', sequence='Sequence_01'):\n",
    "    \"\"\"\n",
    "    Charge et fusionne les données de capteurs (insoles.csv) et \n",
    "    les annotations (classif.csv) d'un sujet et d'une séquence spécifique.\n",
    "    Fréquence : 100 fps. Séparateur : ';'\n",
    "    \"\"\"\n",
    "    insoles_path = os.path.join(PLANTAR_DIR, f\"S{subject_id}\", sequence, \"insoles.csv\")\n",
    "    classif_path = os.path.join(EVENTS_DIR, f\"S{subject_id}\", sequence, \"classif.csv\")\n",
    "    \n",
    "    if not os.path.exists(insoles_path):\n",
    "        print(f\"⚠️ Le fichier {insoles_path} est introuvable.\")\n",
    "        return None\n",
    "        \n",
    "    if not os.path.exists(classif_path):\n",
    "        print(f\"⚠️ Le fichier {classif_path} est introuvable.\")\n",
    "        return None\n",
    "        \n",
    "    print(f\"✅ Chargement des données pour le sujet S{subject_id} - {sequence}\")\n",
    "    \n",
    "    # Chargement (avec séparateur point-virgule comme spécifié)\n",
    "    df_insoles = pd.read_csv(insoles_path, sep=';')\n",
    "    df_classif = pd.read_csv(classif_path, sep=';')\n",
    "    \n",
    "    # Création des colonnes cibles pour stocker les annotations\n",
    "    df_insoles['Class'] = np.nan\n",
    "    df_insoles['Action_Name'] = 'Transition/Unknown'\n",
    "    \n",
    "    # Alignement temporel : pour chaque événement, on l'associe à la plage de temps correspondante\n",
    "    for _, row in df_classif.iterrows():\n",
    "        t_start = row['Timestamp Start']\n",
    "        t_end = row['Timestamp End']\n",
    "        c_id = row['Class']\n",
    "        c_name = row['Name']\n",
    "        \n",
    "        # Création d'un masque pour encadrer chronologiquement l'action\n",
    "        mask = (df_insoles['Time'] >= t_start) & (df_insoles['Time'] <= t_end)\n",
    "        \n",
    "        # Affectation\n",
    "        df_insoles.loc[mask, 'Class'] = c_id\n",
    "        df_insoles.loc[mask, 'Action_Name'] = c_name\n",
    "        \n",
    "    return df_insoles\n",
    "\n",
    "def verify_data_integrity(df):\n",
    "    \"\"\"\n",
    "    Affiche les informations globales et détecte les anomalies (valeurs manquantes ou infinies).\n",
    "    \"\"\"\n",
    "    if df is None: return\n",
    "    \n",
    "    print(\"====== 📋 INFO DU DATASET ======\\n\")\n",
    "    df.info()\n",
    "    \n",
    "    print(\"\\n====== 🧮 STATISTIQUES DESCRIPTIVES (Aperçu des premières colonnes) ======\\n\")\n",
    "    display(df.iloc[:, :15].describe())  # Restriction aux 15 premières colonnes pour la lisibilité\n",
    "    \n",
    "    print(\"\\n====== 🛑 VALEURS MANQUANTES ET INFINIES ======\\n\")\n",
    "    # Compte des valeurs manquantes\n",
    "    missing = df.isna().sum()\n",
    "    nb_missing = missing[missing > 0]\n",
    "    print(f\"-> Colonnes avec valeurs manquantes : {len(nb_missing)}\")\n",
    "    if len(nb_missing) > 0:\n",
    "        print(nb_missing.sort_values(ascending=False).head(5))\n",
    "        \n",
    "    # Compte des valeurs infinies\n",
    "    numeric_cols = df.select_dtypes(include=[np.number]).columns\n",
    "    infinities = np.isinf(df[numeric_cols]).sum()\n",
    "    nb_inf = infinities[infinities > 0]\n",
    "    print(f\"-> Colonnes avec valeurs infinies : {len(nb_inf)}\")\n",
    "    if len(nb_inf) > 0:\n",
    "        print(nb_inf.sort_values(ascending=False).head(5))\n",
    "\n",
    "# Exécution sur la séquence (décommenter une fois les données placées dans les dossiers)\n",
    "df_merged = load_and_merge_data('01', 'Sequence_01')\n",
    "if df_merged is not None:\n",
    "    verify_data_integrity(df_merged)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 2. Analyse Statistique et Outliers\n",
    "\n",
    "Nous traçons la distribution des classes (bar plot) et recherchons visuellement des anomalies de mesure (outliers) au moyen de boxplots, en se concentrant sur une sélection de capteurs pour maintenir la lisibilité."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "def plot_class_distribution(df):\n",
    "    \"\"\"Génère un Bar Plot du nombre d'échantillons (frames) pour chaque action.\"\"\"\n",
    "    if df is None: return\n",
    "    \n",
    "    plt.figure(figsize=(10, 5))\n",
    "    counts = df['Action_Name'].value_counts()\n",
    "    sns.barplot(x=counts.index, y=counts.values, palette='viridis')\n",
    "    \n",
    "    plt.title('Distribution des Actions (Nb d\\'échantillons par action)', fontweight='bold')\n",
    "    plt.xlabel('Action / Classe')\n",
    "    plt.ylabel('Fréquence (Frames)')\n",
    "    plt.xticks(rotation=45, ha='right')\n",
    "    plt.tight_layout()\n",
    "    plt.show()\n",
    "\n",
    "def plot_outliers(df):\n",
    "    \"\"\"Utilise des boxplots pour observer la dispersion et déceler les outliers (IMU et Pressions).\"\"\"\n",
    "    if df is None: return\n",
    "    \n",
    "    # --- 1. Boxplots: Accélérations (IMU) ---\n",
    "    # Recherche automatique basée sur des substrings (acc et xyz ou l/r)\n",
    "    acc_cols = [c for c in df.columns if 'acc' in c.lower()]\n",
    "    \n",
    "    if acc_cols:\n",
    "        plt.figure(figsize=(12, 6))\n",
    "        sns.boxplot(data=df[acc_cols], palette='Set2')\n",
    "        plt.title('Visualisation des Outliers : Accélérations (IMU)', fontweight='bold')\n",
    "        plt.xticks(rotation=45)\n",
    "        plt.ylabel('Valeur d\\'Accélération')\n",
    "        plt.tight_layout()\n",
    "        plt.show()\n",
    "    \n",
    "    # --- 2. Boxplots: Pressions (Focus sur le pied gauche 16 valeurs) ---\n",
    "    # Recherche des colonnes de pression gauche\n",
    "    press_cols = [c for c in df.columns if ('press' in c.lower() or 'pr_' in c.lower()) and ('_l' in c.lower() or 'left' in c.lower())]\n",
    "    \n",
    "    # Fallback si noms inconnus, on prend les premières\n",
    "    if not press_cols:\n",
    "        press_cols = [c for c in df.columns if 'press' in c.lower() or 'pr_' in c.lower()]\n",
    "        \n",
    "    if press_cols:\n",
    "        plt.figure(figsize=(14, 6))\n",
    "        sns.boxplot(data=df[press_cols[:16]], palette='Set3') # Limitation à 16 capteurs\n",
    "        plt.title('Visualisation des Outliers : Capteurs de pression (Gauche)', fontweight='bold')\n",
    "        plt.xticks(rotation=90)\n",
    "        plt.ylabel('Pression (Valeur brute)')\n",
    "        plt.tight_layout()\n",
    "        plt.show()\n",
    "\n",
    "if df_merged is not None:\n",
    "    plot_class_distribution(df_merged)\n",
    "    plot_outliers(df_merged)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 3. Visualisation Spatio-Temporelle des Signaux\n",
    "\n",
    "Pour éviter de tracer des sauts temporels dus aux répétitions de l'action, nous isolons spécifiquement la **première séquence en continu** d'une action ciblée (par exemple \"Walking\")."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "def visualize_signals_window(df, target_action=\"Walking\"):\n",
    "    \"\"\"\n",
    "    Restreint les données à l'action visée, et trace la moyenne des pressions, les\n",
    "    trois axes de l'IMU et le chemin du Centre de Pression (CoP) sur un bloc temporel.\n",
    "    \"\"\"\n",
    "    if df is None: return\n",
    "    \n",
    "    df_action = df[df['Action_Name'] == target_action].copy()\n",
    "    if df_action.empty:\n",
    "        print(f\"⚠️ Aucune donnée pour l'action '{target_action}'.\")\n",
    "        return\n",
    "        \n",
    "    # Extraction de la PREMIÈRE séquence ininterrompue\n",
    "    # Si l'écart de temps dépasse 2 frames (0.02s à 100fps), on considère une coupure.\n",
    "    blocks = (df_action['Time'].diff() > 0.02).cumsum()\n",
    "    df_window = df_action[blocks == blocks.iloc[0]]\n",
    "    time_arr = df_window['Time']\n",
    "    \n",
    "    print(f\"🎬 Étude temporelle [{target_action}] de {time_arr.min():.2f}s à {time_arr.max():.2f}s\")\n",
    "    \n",
    "    # ==================\n",
    "    # 3.A. PRESSIONS MOYENNES (G vs D)\n",
    "    # ==================\n",
    "    press_L = [c for c in df_window.columns if ('press' in c.lower() or 'pr_' in c.lower()) and ('_l' in c.lower() or 'left' in c.lower())][:16]\n",
    "    press_R = [c for c in df_window.columns if ('press' in c.lower() or 'pr_' in c.lower()) and ('_r' in c.lower() or 'right' in c.lower())][:16]\n",
    "    \n",
    "    if press_L and press_R:\n",
    "        mean_L = df_window[press_L].mean(axis=1)\n",
    "        mean_R = df_window[press_R].mean(axis=1)\n",
    "        \n",
    "        plt.figure(figsize=(12, 4))\n",
    "        plt.plot(time_arr, mean_L, label='Gauches Moyennes', color='royalblue', lw=2)\n",
    "        plt.plot(time_arr, mean_R, label='Droites Moyennes', color='firebrick', lw=2)\n",
    "        plt.title(f'Activation Plantaire Moyenne par pied - {target_action}', fontweight='bold')\n",
    "        plt.xlabel('Temps chronologique (s)')\n",
    "        plt.ylabel('Pression moyenne')\n",
    "        plt.legend()\n",
    "        plt.tight_layout()\n",
    "        plt.show()\n",
    "        \n",
    "    # ==================\n",
    "    # 3.B. IMU (Accélération Pied Droit)\n",
    "    # ==================\n",
    "    acc_R = [c for c in df_window.columns if 'acc' in c.lower() and ('_r' in c.lower() or 'right' in c.lower())][:3]\n",
    "    if len(acc_R) == 3:\n",
    "        ax, ay, az = acc_R\n",
    "        plt.figure(figsize=(12, 4))\n",
    "        plt.plot(time_arr, df_window[ax], label=f'Axe X ({ax})', alpha=0.8)\n",
    "        plt.plot(time_arr, df_window[ay], label=f'Axe Y ({ay})', alpha=0.8)\n",
    "        plt.plot(time_arr, df_window[az], label=f'Axe Z ({az})', alpha=0.8)\n",
    "        plt.title(f'Données inertielles (Accélération Pied Droit) - {target_action}', fontweight='bold')\n",
    "        plt.xlabel('Temps chronologique (s)')\n",
    "        plt.ylabel('Accélération transmise')\n",
    "        plt.legend(loc=\"upper right\")\n",
    "        plt.tight_layout()\n",
    "        plt.show()\n",
    "        \n",
    "    # ==================\n",
    "    # 3.C. CENTRE DE PRESSION (CoP Pied Droit)\n",
    "    # ==================\n",
    "    cop_R = [c for c in df_window.columns if 'cop' in c.lower() and ('_r' in c.lower() or 'right' in c.lower())][:2]\n",
    "    if len(cop_R) == 2:\n",
    "        cx, cy = cop_R\n",
    "        plt.figure(figsize=(7, 6))\n",
    "        # Représentation de l'écoulement temporel par la couleur\n",
    "        scatter = plt.scatter(df_window[cx], df_window[cy], c=time_arr, cmap='plasma', s=45)\n",
    "        # Ligne d'historique\n",
    "        plt.plot(df_window[cx], df_window[cy], c='grey', linestyle='-', lw=1, alpha=0.4)\n",
    "        \n",
    "        plt.title(f'Trajectoire 2D du Centre de Pression (Pied Droit) - {target_action}', fontweight='bold')\n",
    "        plt.xlabel(cx)\n",
    "        plt.ylabel(cy)\n",
    "        cbar = plt.colorbar(scatter)\n",
    "        cbar.set_label('Temps parcouru (s)')\n",
    "        plt.grid(True)\n",
    "        plt.tight_layout()\n",
    "        plt.show()\n",
    "\n",
    "if df_merged is not None:\n",
    "    visualize_signals_window(df_merged, target_action=\"Walking\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 4. Comparaison inter-classes\n",
    "\n",
    "Ce module permet de comprendre la variation de magnitudes des efforts totaux (Total Force) entre plusieurs positions (par exemple de \"Standing\" et \"Walking\")."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "def compare_total_force_by_action(df, class1=\"Standing\", class2=\"Walking\"):\n",
    "    \"\"\"\n",
    "    Génère un boxplot et/ou barplot quantitatif de la \"Total Force\" sur deux ou plusieurs actions comparées.\n",
    "    \"\"\"\n",
    "    if df is None: return\n",
    "    \n",
    "    df_comp = df[df['Action_Name'].isin([class1, class2])].copy()\n",
    "    force_cols = [c for c in df.columns if 'total' in c.lower() and 'force' in c.lower()]\n",
    "    \n",
    "    if df_comp.empty or not force_cols:\n",
    "        print(f\"⚠️ Soit les classes n'existent pas, soit la colonne Total Force manque.\")\n",
    "        return\n",
    "        \n",
    "    # Scénario A : Nous avons deux colonnes (Force Totale Gauche, Force Totale Droite)\n",
    "    if len(force_cols) >= 2:\n",
    "        fL, fR = force_cols[0], force_cols[1]\n",
    "        # Transformation en tableau long (Melt) pour Seaborn Hue\n",
    "        df_melt = pd.melt(df_comp, id_vars=['Action_Name'], value_vars=[fL, fR], \n",
    "                          var_name='Côté / Source', value_name='Valeur Force Totale')\n",
    "        \n",
    "        plt.figure(figsize=(9, 6))\n",
    "        sns.barplot(data=df_melt, x='Action_Name', y='Valeur Force Totale', hue='Côté / Source', palette='Set1', capsize=0.1)\n",
    "        plt.title(f'Disparité de Force Totale Bilatérale : {class1} vs {class2}', fontweight='bold')\n",
    "        plt.xlabel('Action ciblée')\n",
    "        plt.ylabel('Moyenne de la Force Totale')\n",
    "        plt.tight_layout()\n",
    "        plt.show()\n",
    "        \n",
    "    # Scénario B : Une seule colonne agglomérée\n",
    "    else:\n",
    "        fc = force_cols[0]\n",
    "        plt.figure(figsize=(8, 6))\n",
    "        sns.boxplot(data=df_comp, x='Action_Name', y=fc, palette='pastel')\n",
    "        plt.title(f'Disparité de Force Totale Globale : {class1} vs {class2}', fontweight='bold')\n",
    "        plt.xlabel('Action ciblée')\n",
    "        plt.ylabel(fc)\n",
    "        plt.tight_layout()\n",
    "        plt.show()\n",
    "\n",
    "if df_merged is not None:\n",
    "    compare_total_force_by_action(df_merged, class1=\"Standing\", class2=\"Walking\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}

with open("EDA_Plantar.ipynb", "w", encoding="utf-8") as f:
    json.dump(notebook, f, indent=1, ensure_ascii=False)
